### PR TITLE
feat: histoprint show

### PR DESCRIPTION
**Pull request by LovelyBuggies**

### CODE REVIEW

**Comment by LovelyBuggies** [comment]
Add the most basic show. You can add args into `show` to adjust the histoprint in the future.

**Comment by henryiii** [comment]
What happens if this is a 2D histogram?

**Comment by LovelyBuggies** [comment]
> What happens if this is a 2D histogram?

```bash
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/hist/lib/python3.8/site-packages/histoprint/formatter.py in get_count_edges(hist)
    518     try:
--> 519         count, edges = hist
    520     except ValueError:

ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-10-9eee2bbaa978> in <module>
      7 
      8 # fill by names
----> 9 h.show()

~/Documents/GitHub/hist/src/hist/basehist.py in show(self)
    370         """
    371 
--> 372         return histoprint.print_hist(self)
    373 
    374     def plot(self, *args, **kwargs) -> matplotlib.artist.Artist:

~/anaconda3/envs/hist/lib/python3.8/site-packages/histoprint/formatter.py in print_hist(hist, file, **kwargs)
    537     """
    538 
--> 539     count, edges = get_count_edges(hist)
    540     hist_formatter = HistFormatter(edges, **kwargs)
    541     click.echo(hist_formatter.format_histogram(count), nl=False, file=file)

~/anaconda3/envs/hist/lib/python3.8/site-packages/histoprint/formatter.py in get_count_edges(hist)
    519         count, edges = hist
    520     except ValueError:
--> 521         raise ValueError("Not a compatible histogram!")
    522 
    523     return count, edges

ValueError: Not a compatible histogram!
```

**Comment by henryiii** [comment]
Not a fantastic error, but not too bad. Probably will be better to leave it to histoprint to make a better one.

**Comment by henryiii** [comment]
Should we just pass through `**kwargs` for now?

**Pull request merged**
