### PR TITLE
feat: adding something like the classic hist

### PR DESCRIPTION
**Pull request by henryiii**
Addressing #35. 

Currently it seems that axes without names are broken in Hist. If I do a new `pip install -e .[dev]`, then try, from a command line:

```bash
hist
1
2
3
2
```
Then press control-D, I get:

```python
Traceback (most recent call last):
  File "/Users/henryschreiner/git/scikit-hep/hist/.env/bin/hist", line 33, in <module>
    sys.exit(load_entry_point('hist', 'console_scripts', 'hist')())
  File "/Users/henryschreiner/git/scikit-hep/hist/src/hist/classic_hist.py", line 22, in main
    h = bh.numpy.histogram(values, bins=args.buckets, histogram=hist.Hist)
  File "/Users/henryschreiner/git/scikit-hep/hist/.env/lib/python3.8/site-packages/boost_histogram/numpy.py", line 111, in histogram
    return histogramdd((a,), (bins,), (range,), normed, weights, density, **kwargs)
  File "/Users/henryschreiner/git/scikit-hep/hist/.env/lib/python3.8/site-packages/boost_histogram/numpy.py", line 74, in histogramdd
    hist = cls(*axs, storage=bh_storage).fill(*a, weight=weights, threads=threads)
  File "/Users/henryschreiner/git/scikit-hep/hist/src/hist/core.py", line 38, in __init__
    if ax.name in self.names:
  File "/Users/henryschreiner/git/scikit-hep/hist/src/hist/_internal/axis.py", line 52, in name
    return self.metadata["name"]
TypeError: 'NoneType' object is not subscriptable
```

@LovelyBuggies, could you take a look? This is really just running `bh.numpy.histogram([1,2,3,2], histogram=hist.Hist)`.

### CODE REVIEW

**Comment by henryiii** [comment]
Added two tests that should pass, but don't.

**Comment by henryiii** [comment]
Git has trouble tracking changes to the file that was moved and changed at the same time. Normally git is fine if a file is moved, but the move and the change must happen in separate commits and not be squashed.

**Comment by LovelyBuggies** [comment]
> Git has trouble tracking changes to the file that was moved and changed at the same time. Normally git is fine if a file is moved, but the move and the change must happen in separate commits and not be squashed.

Doesn't matter. The main reason that causes the test failed is that you have non-named axes in Hist. But axis names should not be duplicated.

**Comment by henryiii** [comment]
Non-named axes are explicitly allowed in Hist, that's the difference between Hist and NamedHist. Hist allows names but does not require them, and NamedHist forces names.

What we should do is in the check for duplicate names, simply ignore None (or all False-like might be better), so those don't count in the uniqueness check.

**Comment by LovelyBuggies** [comment]
> simply ignore None 

Exactly.

**Comment by henryiii** [comment]
Feel free to add `@pytest.mark.xfail` for tests you plan to fix later. https://docs.pytest.org/en/latest/skipping.html

**Comment by LovelyBuggies** [comment]
> Feel free to add `@pytest.mark.xfail` for tests you plan to fix later. https://docs.pytest.org/en/latest/skipping.html

I have figured it out. But shortcuts' tests are a little cursory. Merge this if the classic hist is alright, and I will open a new PR to expand these tests later.

**Comment by henryiii** [comment]
We should add an integration test. I’ll have to suggest something.

In conda, this should be pretty much automatically available, bin works the same way, though it might be nice to add histoprint to conda if we add Hist to conda.

**Comment by LovelyBuggies** [comment]
I expect we can walk on two legs, that is we can dev and users are allowed by both conda and venv :)

**Pull request merged**
