### PR TITLE
boost-histogram and histoprint dependencies update

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**
Can this be released as 2.1.0 so that we get a consistent set of packages for the next `scikit-hep` metapackage release, see https://github.com/scikit-hep/scikit-hep/pull/133? Advance thanks.

### CODE REVIEW

**Comment by henryiii** [comment]
Boost-histogram 0.13 out! I'll update and do a bit of testing, add the storage= shortcuts, then release 1.1, should be today or tomorrow.

**Comment by eduardo-rodrigues** [comment]
You mean release 2.1, I'm sure. Sounds great, thanks for the updates.

**Comment by henryiii** [comment]
Yes, that's what I meant. Sorry, my brain is fried (as @HDembinski already knows). :) 👶 

Waiting on a bug in mplhep, matplotlib doesn't like getting an alias kw argument and the insulated name; hoping @andrzejnovak can fix.

**Comment by henryiii** [comment]
Worked around the but for now, will be much nicer when fixed upstream, but that way a release was not delayed. Hist 2.1 is now released. The PlottableHistogram Protocol is now available in boost-histogram 0.13.0, hist 2.1.0, uproot 4, and mplhep 0.2.16! I'm not sure about histoprint.

**Pull request merged**
